### ISSUE TITLE
Can I use this with React or React native?

### ISSUE THREAD

**Issue by MichelDiz** [itconsultis/prestashop-api-client#1]
Just asking, I'm gonna try myself right now.

I'm testing fetch() but I can't get it done with the auth key

thanks!

Best Regards

**Comment by rich-choy** [comment]
Hi @MichelDiz,

This package is meant to be consumed server-side, but you should be able to use it in the browser *if you are willing to expose the Prestashop API key* (which I don't recommend). You would have to instantiate a Client this way:

```javascript
import {rest} from 'prestashop-api-client';

let client = new rest.Client({
  fetch: {
    algo: window.fetch
  },
  webservice: {
    key: 'your-webservice-key',
    scheme: 'https',
    host: 'your-prestashop-host',
  },
})
```

**Comment by MichelDiz** [comment]
Hey I'm trying this https://github.com/tigerraj32/web-service-handler/issues/1

**Comment by MichelDiz** [comment]
By the way something got wrong with this project "prestashop-api-client". The NPM (or maybe React Native it self) was deleting automatically all packages and cleaning package.json without warning

**Comment by rich-choy** [comment]
Can you show me how to reproduce the problem?

**Comment by MichelDiz** [comment]
Well I did cmd "react-native init Someprojetc" > tried npm install prestashop-api-client --save (tried also yarn add prestashop-api-client) Both get install correctly:

PS. Also I did "React-native link"
My machine:

Windows 10
react-native-cli: 1.3.0
react-native: 0.39.2
Visual Studio Code

I think that some incompatibility with RN so. Or I'm wrong?
